const CACHE_PREFIX = "cookie-arcade-offline-";

// BEGIN GENERATED OFFLINE MANIFEST
const CACHE_VERSION = "4ef628ab95189408";
const PRECACHE_PATHS = [
  "./",
  "./apple-touch-icon.png",
  "./games/_lib/stage.js",
  "./games/_lib/twirlywoos.js",
  "./games/_lib/words-data.js",
  "./games/animals/",
  "./games/animals/audio/bee.mp3",
  "./games/animals/audio/bird.mp3",
  "./games/animals/audio/cat.mp3",
  "./games/animals/audio/chicken.mp3",
  "./games/animals/audio/cow.mp3",
  "./games/animals/audio/dog.mp3",
  "./games/animals/audio/duck.mp3",
  "./games/animals/audio/elephant.mp3",
  "./games/animals/audio/frog.mp3",
  "./games/animals/audio/horse.mp3",
  "./games/animals/audio/lion.mp3",
  "./games/animals/audio/monkey.mp3",
  "./games/animals/audio/mouse.mp3",
  "./games/animals/audio/pig.mp3",
  "./games/animals/audio/rabbit.mp3",
  "./games/animals/audio/sheep.mp3",
  "./games/animals/audio/tiger.mp3",
  "./games/animals/index.html",
  "./games/basket/",
  "./games/basket/audio/count_1.mp3",
  "./games/basket/audio/count_2.mp3",
  "./games/basket/audio/count_3.mp3",
  "./games/basket/audio/count_4.mp3",
  "./games/basket/audio/count_5.mp3",
  "./games/basket/audio/done_apple_3.mp3",
  "./games/basket/audio/done_apple_4.mp3",
  "./games/basket/audio/done_apple_5.mp3",
  "./games/basket/audio/done_banana_3.mp3",
  "./games/basket/audio/done_banana_4.mp3",
  "./games/basket/audio/done_banana_5.mp3",
  "./games/basket/audio/done_orange_3.mp3",
  "./games/basket/audio/done_orange_4.mp3",
  "./games/basket/audio/done_orange_5.mp3",
  "./games/basket/audio/done_strawberry_3.mp3",
  "./games/basket/audio/done_strawberry_4.mp3",
  "./games/basket/audio/done_strawberry_5.mp3",
  "./games/basket/audio/intro_apple.mp3",
  "./games/basket/audio/intro_banana.mp3",
  "./games/basket/audio/intro_orange.mp3",
  "./games/basket/audio/intro_strawberry.mp3",
  "./games/basket/index.html",
  "./games/bath/",
  "./games/bath/audio/clean_cat.mp3",
  "./games/bath/audio/clean_chicken.mp3",
  "./games/bath/audio/clean_cow.mp3",
  "./games/bath/audio/clean_dog.mp3",
  "./games/bath/audio/clean_elephant.mp3",
  "./games/bath/audio/clean_monkey.mp3",
  "./games/bath/audio/clean_panda.mp3",
  "./games/bath/audio/clean_rabbit.mp3",
  "./games/bath/audio/dirty_cat.mp3",
  "./games/bath/audio/dirty_chicken.mp3",
  "./games/bath/audio/dirty_cow.mp3",
  "./games/bath/audio/dirty_dog.mp3",
  "./games/bath/audio/dirty_elephant.mp3",
  "./games/bath/audio/dirty_monkey.mp3",
  "./games/bath/audio/dirty_panda.mp3",
  "./games/bath/audio/dirty_rabbit.mp3",
  "./games/bath/index.html",
  "./games/bubbles/",
  "./games/bubbles/index.html",
  "./games/bus/",
  "./games/bus/audio/aboard.mp3",
  "./games/bus/audio/board_first.mp3",
  "./games/bus/audio/bye.mp3",
  "./games/bus/audio/close.mp3",
  "./games/bus/audio/close_first.mp3",
  "./games/bus/audio/go.mp3",
  "./games/bus/audio/leave_first.mp3",
  "./games/bus/audio/look.mp3",
  "./games/bus/audio/not_yet.mp3",
  "./games/bus/audio/open.mp3",
  "./games/bus/audio/open_first.mp3",
  "./games/bus/audio/ready.mp3",
  "./games/bus/audio/stop_beach.mp3",
  "./games/bus/audio/stop_home.mp3",
  "./games/bus/audio/stop_park.mp3",
  "./games/bus/index.html",
  "./games/cars/",
  "./games/cars/audio/ambulance.mp3",
  "./games/cars/audio/bus.mp3",
  "./games/cars/audio/car.mp3",
  "./games/cars/audio/firetruck.mp3",
  "./games/cars/audio/motorbike.mp3",
  "./games/cars/audio/police.mp3",
  "./games/cars/audio/tractor.mp3",
  "./games/cars/audio/train.mp3",
  "./games/cars/audio/truck.mp3",
  "./games/cars/index.html",
  "./games/cascade/",
  "./games/cascade/index.html",
  "./games/drums/",
  "./games/drums/index.html",
  "./games/echo/",
  "./games/echo/audio/again.mp3",
  "./games/echo/audio/intro.mp3",
  "./games/echo/audio/listen.mp3",
  "./games/echo/audio/yay_1.mp3",
  "./games/echo/audio/yay_2.mp3",
  "./games/echo/audio/yay_3.mp3",
  "./games/echo/audio/your_turn_1.mp3",
  "./games/echo/audio/your_turn_2.mp3",
  "./games/echo/index.html",
  "./games/elevator/",
  "./games/elevator/audio/above.mp3",
  "./games/elevator/audio/below.mp3",
  "./games/elevator/audio/bottom.mp3",
  "./games/elevator/audio/close_first.mp3",
  "./games/elevator/audio/closing.mp3",
  "./games/elevator/audio/door_closed.mp3",
  "./games/elevator/audio/door_open.mp3",
  "./games/elevator/audio/down.mp3",
  "./games/elevator/audio/hello.mp3",
  "./games/elevator/audio/home_bear.mp3",
  "./games/elevator/audio/home_cat.mp3",
  "./games/elevator/audio/home_rabbit.mp3",
  "./games/elevator/audio/look.mp3",
  "./games/elevator/audio/opening.mp3",
  "./games/elevator/audio/task_bear.mp3",
  "./games/elevator/audio/task_cat.mp3",
  "./games/elevator/audio/task_rabbit.mp3",
  "./games/elevator/audio/top.mp3",
  "./games/elevator/audio/up.mp3",
  "./games/elevator/index.html",
  "./games/feed/",
  "./games/feed/audio/fav_cat.mp3",
  "./games/feed/audio/fav_chicken.mp3",
  "./games/feed/audio/fav_cow.mp3",
  "./games/feed/audio/fav_dog.mp3",
  "./games/feed/audio/fav_elephant.mp3",
  "./games/feed/audio/fav_monkey.mp3",
  "./games/feed/audio/fav_panda.mp3",
  "./games/feed/audio/fav_rabbit.mp3",
  "./games/feed/audio/full_cat.mp3",
  "./games/feed/audio/full_chicken.mp3",
  "./games/feed/audio/full_cow.mp3",
  "./games/feed/audio/full_dog.mp3",
  "./games/feed/audio/full_elephant.mp3",
  "./games/feed/audio/full_monkey.mp3",
  "./games/feed/audio/full_panda.mp3",
  "./games/feed/audio/full_rabbit.mp3",
  "./games/feed/audio/no_1.mp3",
  "./games/feed/audio/no_2.mp3",
  "./games/feed/audio/no_3.mp3",
  "./games/feed/audio/yum_1.mp3",
  "./games/feed/audio/yum_2.mp3",
  "./games/feed/audio/yum_3.mp3",
  "./games/feed/index.html",
  "./games/find/",
  "./games/find/audio/q_apple.mp3",
  "./games/find/audio/q_baba.mp3",
  "./games/find/audio/q_ball.mp3",
  "./games/find/audio/q_banana.mp3",
  "./games/find/audio/q_baobao.mp3",
  "./games/find/audio/q_bath.mp3",
  "./games/find/audio/q_biscuit.mp3",
  "./games/find/audio/q_boat.mp3",
  "./games/find/audio/q_book.mp3",
  "./games/find/audio/q_bread.mp3",
  "./games/find/audio/q_car.mp3",
  "./games/find/audio/q_clap.mp3",
  "./games/find/audio/q_cloud.mp3",
  "./games/find/audio/q_cry.mp3",
  "./games/find/audio/q_ear.mp3",
  "./games/find/audio/q_egg.mp3",
  "./games/find/audio/q_eye.mp3",
  "./games/find/audio/q_flower.mp3",
  "./games/find/audio/q_foot.mp3",
  "./games/find/audio/q_grape.mp3",
  "./games/find/audio/q_hand.mp3",
  "./games/find/audio/q_hat.mp3",
  "./games/find/audio/q_hug.mp3",
  "./games/find/audio/q_lamp.mp3",
  "./games/find/audio/q_laugh.mp3",
  "./games/find/audio/q_mama.mp3",
  "./games/find/audio/q_milk.mp3",
  "./games/find/audio/q_moon.mp3",
  "./games/find/audio/q_mouth.mp3",
  "./games/find/audio/q_nainai.mp3",
  "./games/find/audio/q_noodle.mp3",
  "./games/find/audio/q_nose.mp3",
  "./games/find/audio/q_orange.mp3",
  "./games/find/audio/q_plane.mp3",
  "./games/find/audio/q_rain.mp3",
  "./games/find/audio/q_rainbow.mp3",
  "./games/find/audio/q_rice.mp3",
  "./games/find/audio/q_shoe.mp3",
  "./games/find/audio/q_sleep.mp3",
  "./games/find/audio/q_snowman.mp3",
  "./games/find/audio/q_sock.mp3",
  "./games/find/audio/q_spoon.mp3",
  "./games/find/audio/q_star.mp3",
  "./games/find/audio/q_strawberry.mp3",
  "./games/find/audio/q_sun.mp3",
  "./games/find/audio/q_train.mp3",
  "./games/find/audio/q_tree.mp3",
  "./games/find/audio/q_umbrella.mp3",
  "./games/find/audio/q_watermelon.mp3",
  "./games/find/audio/q_yeye.mp3",
  "./games/find/audio/y_apple.mp3",
  "./games/find/audio/y_baba.mp3",
  "./games/find/audio/y_ball.mp3",
  "./games/find/audio/y_banana.mp3",
  "./games/find/audio/y_baobao.mp3",
  "./games/find/audio/y_bath.mp3",
  "./games/find/audio/y_biscuit.mp3",
  "./games/find/audio/y_boat.mp3",
  "./games/find/audio/y_book.mp3",
  "./games/find/audio/y_bread.mp3",
  "./games/find/audio/y_car.mp3",
  "./games/find/audio/y_clap.mp3",
  "./games/find/audio/y_cloud.mp3",
  "./games/find/audio/y_cry.mp3",
  "./games/find/audio/y_ear.mp3",
  "./games/find/audio/y_egg.mp3",
  "./games/find/audio/y_eye.mp3",
  "./games/find/audio/y_flower.mp3",
  "./games/find/audio/y_foot.mp3",
  "./games/find/audio/y_grape.mp3",
  "./games/find/audio/y_hand.mp3",
  "./games/find/audio/y_hat.mp3",
  "./games/find/audio/y_hug.mp3",
  "./games/find/audio/y_lamp.mp3",
  "./games/find/audio/y_laugh.mp3",
  "./games/find/audio/y_mama.mp3",
  "./games/find/audio/y_milk.mp3",
  "./games/find/audio/y_moon.mp3",
  "./games/find/audio/y_mouth.mp3",
  "./games/find/audio/y_nainai.mp3",
  "./games/find/audio/y_noodle.mp3",
  "./games/find/audio/y_nose.mp3",
  "./games/find/audio/y_orange.mp3",
  "./games/find/audio/y_plane.mp3",
  "./games/find/audio/y_rain.mp3",
  "./games/find/audio/y_rainbow.mp3",
  "./games/find/audio/y_rice.mp3",
  "./games/find/audio/y_shoe.mp3",
  "./games/find/audio/y_sleep.mp3",
  "./games/find/audio/y_snowman.mp3",
  "./games/find/audio/y_sock.mp3",
  "./games/find/audio/y_spoon.mp3",
  "./games/find/audio/y_star.mp3",
  "./games/find/audio/y_strawberry.mp3",
  "./games/find/audio/y_sun.mp3",
  "./games/find/audio/y_train.mp3",
  "./games/find/audio/y_tree.mp3",
  "./games/find/audio/y_umbrella.mp3",
  "./games/find/audio/y_watermelon.mp3",
  "./games/find/audio/y_yeye.mp3",
  "./games/find/index.html",
  "./games/helper/",
  "./games/helper/audio/first_take.mp3",
  "./games/helper/audio/got_apple.mp3",
  "./games/helper/audio/got_ball.mp3",
  "./games/helper/audio/got_banana.mp3",
  "./games/helper/audio/got_cup.mp3",
  "./games/helper/audio/got_hat.mp3",
  "./games/helper/audio/no_animal_bear.mp3",
  "./games/helper/audio/no_animal_bunny.mp3",
  "./games/helper/audio/no_animal_cat.mp3",
  "./games/helper/audio/no_animal_dog.mp3",
  "./games/helper/audio/no_item_apple.mp3",
  "./games/helper/audio/no_item_ball.mp3",
  "./games/helper/audio/no_item_banana.mp3",
  "./games/helper/audio/no_item_cup.mp3",
  "./games/helper/audio/no_item_hat.mp3",
  "./games/helper/audio/task_apple_bear.mp3",
  "./games/helper/audio/task_apple_bunny.mp3",
  "./games/helper/audio/task_apple_cat.mp3",
  "./games/helper/audio/task_apple_dog.mp3",
  "./games/helper/audio/task_ball_bear.mp3",
  "./games/helper/audio/task_ball_bunny.mp3",
  "./games/helper/audio/task_ball_cat.mp3",
  "./games/helper/audio/task_ball_dog.mp3",
  "./games/helper/audio/task_banana_bear.mp3",
  "./games/helper/audio/task_banana_bunny.mp3",
  "./games/helper/audio/task_banana_cat.mp3",
  "./games/helper/audio/task_banana_dog.mp3",
  "./games/helper/audio/task_cup_bear.mp3",
  "./games/helper/audio/task_cup_bunny.mp3",
  "./games/helper/audio/task_cup_cat.mp3",
  "./games/helper/audio/task_cup_dog.mp3",
  "./games/helper/audio/task_hat_bear.mp3",
  "./games/helper/audio/task_hat_bunny.mp3",
  "./games/helper/audio/task_hat_cat.mp3",
  "./games/helper/audio/task_hat_dog.mp3",
  "./games/helper/audio/thanks_bear.mp3",
  "./games/helper/audio/thanks_bunny.mp3",
  "./games/helper/audio/thanks_cat.mp3",
  "./games/helper/audio/thanks_dog.mp3",
  "./games/helper/audio/yay_1.mp3",
  "./games/helper/audio/yay_2.mp3",
  "./games/helper/audio/yay_3.mp3",
  "./games/helper/index.html",
  "./games/keyboard/",
  "./games/keyboard/index.html",
  "./games/outing/",
  "./games/outing/audio/bye_1.mp3",
  "./games/outing/audio/bye_2.mp3",
  "./games/outing/audio/go_bottle.mp3",
  "./games/outing/audio/go_cap.mp3",
  "./games/outing/audio/go_car.mp3",
  "./games/outing/audio/go_shirt.mp3",
  "./games/outing/audio/go_shoe.mp3",
  "./games/outing/audio/go_sock.mp3",
  "./games/outing/audio/go_towel.mp3",
  "./games/outing/audio/go_umbrella.mp3",
  "./games/outing/audio/go_weather.mp3",
  "./games/outing/audio/hint_car_wait.mp3",
  "./games/outing/audio/hint_milk_first.mp3",
  "./games/outing/audio/hint_rain.mp3",
  "./games/outing/audio/hint_sock_first.mp3",
  "./games/outing/audio/hint_sun.mp3",
  "./games/outing/audio/intro.mp3",
  "./games/outing/audio/next.mp3",
  "./games/outing/audio/ok_bottle.mp3",
  "./games/outing/audio/ok_cap.mp3",
  "./games/outing/audio/ok_car.mp3",
  "./games/outing/audio/ok_shirt.mp3",
  "./games/outing/audio/ok_shoe.mp3",
  "./games/outing/audio/ok_sock.mp3",
  "./games/outing/audio/ok_towel.mp3",
  "./games/outing/audio/ok_umbrella.mp3",
  "./games/outing/audio/weather_rain.mp3",
  "./games/outing/audio/weather_sun.mp3",
  "./games/outing/index.html",
  "./games/peekaboo/",
  "./games/peekaboo/audio/bear.mp3",
  "./games/peekaboo/audio/cat.mp3",
  "./games/peekaboo/audio/chick.mp3",
  "./games/peekaboo/audio/cow.mp3",
  "./games/peekaboo/audio/dog.mp3",
  "./games/peekaboo/audio/fox.mp3",
  "./games/peekaboo/audio/frog.mp3",
  "./games/peekaboo/audio/monkey.mp3",
  "./games/peekaboo/audio/panda.mp3",
  "./games/peekaboo/audio/penguin.mp3",
  "./games/peekaboo/audio/rabbit.mp3",
  "./games/peekaboo/audio/tiger.mp3",
  "./games/peekaboo/index.html",
  "./games/road/",
  "./games/road/audio/choose.mp3",
  "./games/road/audio/go.mp3",
  "./games/road/audio/hint.mp3",
  "./games/road/audio/home.mp3",
  "./games/road/audio/intro.mp3",
  "./games/road/audio/joined.mp3",
  "./games/road/audio/mismatch.mp3",
  "./games/road/audio/next.mp3",
  "./games/road/audio/place.mp3",
  "./games/road/audio/wait.mp3",
  "./games/road/index.html",
  "./games/scribble/",
  "./games/scribble/index.html",
  "./games/shapes/",
  "./games/shapes/audio/q_circle.mp3",
  "./games/shapes/audio/q_heart.mp3",
  "./games/shapes/audio/q_moon.mp3",
  "./games/shapes/audio/q_square.mp3",
  "./games/shapes/audio/q_star.mp3",
  "./games/shapes/audio/q_triangle.mp3",
  "./games/shapes/audio/y_circle.mp3",
  "./games/shapes/audio/y_heart.mp3",
  "./games/shapes/audio/y_moon.mp3",
  "./games/shapes/audio/y_square.mp3",
  "./games/shapes/audio/y_star.mp3",
  "./games/shapes/audio/y_triangle.mp3",
  "./games/shapes/index.html",
  "./games/sleep/",
  "./games/sleep/audio/night_cat.mp3",
  "./games/sleep/audio/night_chicken.mp3",
  "./games/sleep/audio/night_cow.mp3",
  "./games/sleep/audio/night_dog.mp3",
  "./games/sleep/audio/night_elephant.mp3",
  "./games/sleep/audio/night_monkey.mp3",
  "./games/sleep/audio/night_panda.mp3",
  "./games/sleep/audio/night_rabbit.mp3",
  "./games/sleep/audio/sleepy_cat.mp3",
  "./games/sleep/audio/sleepy_chicken.mp3",
  "./games/sleep/audio/sleepy_cow.mp3",
  "./games/sleep/audio/sleepy_dog.mp3",
  "./games/sleep/audio/sleepy_elephant.mp3",
  "./games/sleep/audio/sleepy_monkey.mp3",
  "./games/sleep/audio/sleepy_panda.mp3",
  "./games/sleep/audio/sleepy_rabbit.mp3",
  "./games/sleep/index.html",
  "./games/sort/",
  "./games/sort/audio/done_1.mp3",
  "./games/sort/audio/done_2.mp3",
  "./games/sort/audio/done_3.mp3",
  "./games/sort/audio/intro.mp3",
  "./games/sort/audio/name_blue.mp3",
  "./games/sort/audio/name_green.mp3",
  "./games/sort/audio/name_red.mp3",
  "./games/sort/audio/name_yellow.mp3",
  "./games/sort/audio/no_blue.mp3",
  "./games/sort/audio/no_green.mp3",
  "./games/sort/audio/no_red.mp3",
  "./games/sort/audio/no_yellow.mp3",
  "./games/sort/audio/put_blue.mp3",
  "./games/sort/audio/put_green.mp3",
  "./games/sort/audio/put_red.mp3",
  "./games/sort/audio/put_yellow.mp3",
  "./games/sort/index.html",
  "./games/storybook/",
  "./games/storybook/audio/ask_1.mp3",
  "./games/storybook/audio/ask_2.mp3",
  "./games/storybook/audio/ask_3.mp3",
  "./games/storybook/audio/ask_4.mp3",
  "./games/storybook/audio/finale.mp3",
  "./games/storybook/audio/intro.mp3",
  "./games/storybook/audio/reveal_bighoo.mp3",
  "./games/storybook/audio/reveal_chick.mp3",
  "./games/storybook/audio/reveal_chickedy.mp3",
  "./games/storybook/audio/reveal_toodloo.mp3",
  "./games/storybook/index.html",
  "./games/train/",
  "./games/train/audio/first_cat.mp3",
  "./games/train/audio/first_chicken.mp3",
  "./games/train/audio/first_cow.mp3",
  "./games/train/audio/first_dog.mp3",
  "./games/train/audio/first_elephant.mp3",
  "./games/train/audio/first_monkey.mp3",
  "./games/train/audio/first_panda.mp3",
  "./games/train/audio/first_rabbit.mp3",
  "./games/train/audio/go.mp3",
  "./games/train/audio/intro.mp3",
  "./games/train/audio/last_cat.mp3",
  "./games/train/audio/last_chicken.mp3",
  "./games/train/audio/last_cow.mp3",
  "./games/train/audio/last_dog.mp3",
  "./games/train/audio/last_elephant.mp3",
  "./games/train/audio/last_monkey.mp3",
  "./games/train/audio/last_panda.mp3",
  "./games/train/audio/last_rabbit.mp3",
  "./games/train/audio/next_cat.mp3",
  "./games/train/audio/next_chicken.mp3",
  "./games/train/audio/next_cow.mp3",
  "./games/train/audio/next_dog.mp3",
  "./games/train/audio/next_elephant.mp3",
  "./games/train/audio/next_monkey.mp3",
  "./games/train/audio/next_panda.mp3",
  "./games/train/audio/next_rabbit.mp3",
  "./games/train/audio/no_1.mp3",
  "./games/train/audio/no_2.mp3",
  "./games/train/index.html",
  "./games/tw-bubbles/",
  "./games/tw-bubbles/index.html",
  "./games/tw-chorus/",
  "./games/tw-chorus/index.html",
  "./games/tw-mood/",
  "./games/tw-mood/index.html",
  "./games/tw-more/",
  "./games/tw-more/index.html",
  "./games/tw-summon/",
  "./games/tw-summon/audio/reveal_bighoo.mp3",
  "./games/tw-summon/audio/reveal_chick.mp3",
  "./games/tw-summon/audio/reveal_chickedy.mp3",
  "./games/tw-summon/audio/reveal_toodloo.mp3",
  "./games/tw-summon/index.html",
  "./games/words/",
  "./games/words/audio/apple.mp3",
  "./games/words/audio/baba.mp3",
  "./games/words/audio/ball.mp3",
  "./games/words/audio/banana.mp3",
  "./games/words/audio/baobao.mp3",
  "./games/words/audio/bath.mp3",
  "./games/words/audio/biscuit.mp3",
  "./games/words/audio/boat.mp3",
  "./games/words/audio/book.mp3",
  "./games/words/audio/bread.mp3",
  "./games/words/audio/car.mp3",
  "./games/words/audio/clap.mp3",
  "./games/words/audio/cloud.mp3",
  "./games/words/audio/cry.mp3",
  "./games/words/audio/ear.mp3",
  "./games/words/audio/egg.mp3",
  "./games/words/audio/eye.mp3",
  "./games/words/audio/flower.mp3",
  "./games/words/audio/foot.mp3",
  "./games/words/audio/grape.mp3",
  "./games/words/audio/hand.mp3",
  "./games/words/audio/hat.mp3",
  "./games/words/audio/hug.mp3",
  "./games/words/audio/lamp.mp3",
  "./games/words/audio/laugh.mp3",
  "./games/words/audio/mama.mp3",
  "./games/words/audio/milk.mp3",
  "./games/words/audio/moon.mp3",
  "./games/words/audio/mouth.mp3",
  "./games/words/audio/nainai.mp3",
  "./games/words/audio/noodle.mp3",
  "./games/words/audio/nose.mp3",
  "./games/words/audio/orange.mp3",
  "./games/words/audio/plane.mp3",
  "./games/words/audio/rain.mp3",
  "./games/words/audio/rainbow.mp3",
  "./games/words/audio/rice.mp3",
  "./games/words/audio/shoe.mp3",
  "./games/words/audio/sleep.mp3",
  "./games/words/audio/snowman.mp3",
  "./games/words/audio/sock.mp3",
  "./games/words/audio/spoon.mp3",
  "./games/words/audio/star.mp3",
  "./games/words/audio/strawberry.mp3",
  "./games/words/audio/sun.mp3",
  "./games/words/audio/train.mp3",
  "./games/words/audio/tree.mp3",
  "./games/words/audio/umbrella.mp3",
  "./games/words/audio/watermelon.mp3",
  "./games/words/audio/yeye.mp3",
  "./games/words/index.html",
  "./icon-512.png",
  "./index.html",
  "./manifest.json"
];
// END GENERATED OFFLINE MANIFEST

const CACHE_NAME = CACHE_PREFIX + CACHE_VERSION;

async function precache() {
  const cache = await caches.open(CACHE_NAME);
  const base = new URL(self.registration.scope);
  const requests = PRECACHE_PATHS.map(
    (path) => new Request(new URL(path, base), { cache: "reload" }),
  );
  await cache.addAll(requests);
}

async function rangeResponse(request, response) {
  const match = /^bytes=(\d*)-(\d*)$/i.exec(request.headers.get("range") || "");
  if (!match) return response;

  const body = await response.arrayBuffer();
  const size = body.byteLength;
  if (size === 0) return response;

  let start;
  let end;
  if (match[1] === "") {
    const suffixLength = Number(match[2]);
    if (!Number.isFinite(suffixLength) || suffixLength <= 0) return response;
    start = Math.max(size - suffixLength, 0);
    end = size - 1;
  } else {
    start = Number(match[1]);
    end = match[2] === "" ? size - 1 : Number(match[2]);
  }

  if (
    !Number.isFinite(start) ||
    !Number.isFinite(end) ||
    start < 0 ||
    start >= size ||
    end < start
  ) {
    return new Response(null, {
      status: 416,
      headers: { "Content-Range": `bytes */${size}` },
    });
  }

  end = Math.min(end, size - 1);
  const headers = new Headers(response.headers);
  headers.set("Accept-Ranges", "bytes");
  headers.set("Content-Range", `bytes ${start}-${end}/${size}`);
  headers.set("Content-Length", String(end - start + 1));

  return new Response(body.slice(start, end + 1), {
    status: 206,
    statusText: "Partial Content",
    headers,
  });
}

self.addEventListener("install", (event) => {
  event.waitUntil(precache().then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME)
          .map((name) => caches.delete(name)),
      );
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      const cached = await cache.match(request, { ignoreVary: true });
      if (cached) {
        return request.headers.has("range")
          ? rangeResponse(request, cached)
          : cached;
      }

      try {
        return await fetch(request);
      } catch (error) {
        if (request.mode === "navigate") {
          const fallback = await cache.match(
            new URL("./index.html", self.registration.scope),
          );
          if (fallback) return fallback;
        }
        throw error;
      }
    })(),
  );
});
